"""
@Author: Wiktor Filipiuk <wiktor.filipiuk@gmail.com>
@ProblemName: Highly divisible triangular number
-----------------------------------------------------------------------
@Description:
The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?

"""

from functools import reduce

def generateNumber(n):
    return sum(range(1,n+1))

def findDivisors(n):
    return(set(reduce(list.__add__,([i,n//i] for i in range(1, int(n**0.5)+1) if n%i == 0))))

def findTriangle(t):
    length = 1
    i = 2
    number = 0
    while length <= t:
        number = generateNumber(i)
        divisors = findDivisors(number)
        length = len(divisors)
        i = i + 1
    return(number)

print(findTriangle(500))