"""
@Author: Wiktor Filipiuk <wiktor.filipiuk@gmail.com>
@ProblemName: Even Fibonacci numbers
-------------------------------------------------------------------------
@Description:
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

def generateFibonacci(limit):
    myList = [1,2]
    while myList[-1] + myList[-2] <= limit:
        myList.append(myList[-1] + myList[-2])
    return myList        
    
def sumEvenFibonacci(myList):
    return sum([x for x in myList if x%2 == 0])

x = generateFibonacci(4000000)
print(sumEvenFibonacci(x))